In [1]:
import numpy as np

In [9]:
from scipy.spatial.transform import Rotation
import numpy as np

def create_rotation(array):
    euler_angles = np.radians(array)
    r = Rotation.from_euler('xyz', euler_angles)
    rotation_matrix = r.as_matrix()
    return rotation_matrix

def Rot2Euler(rotation_matrix):
    r = Rotation.from_matrix(rotation_matrix)
    return np.degrees(r.as_euler('xyz'))

In [6]:
def compute(Root, T_pose, status):
    R_Gp_B0 = np.array([
        [ 0.,  0.,  1.],
        [ 1.,  0., -0.],
        [ 0.,  1.,  0.]
    ])
    R_Gn_Gp = Root
    R_Gn_S0 = T_pose
    
    R_Gp_S0 = R_Gn_Gp.transpose().dot(R_Gn_S0)
    R_B0_S0 = R_Gp_B0.transpose().dot(R_Gp_S0)
    
    R_Gn_St = status
    R_Gp_St =  R_Gn_Gp.transpose().dot(R_Gn_St)
    R_Gp_Bt = R_Gp_St.dot(R_B0_S0.transpose())
    
    return R_Gp_Bt

In [62]:
Root = create_rotation(
    [0, 0, 0]
)
T_pose = create_rotation(
    [0, 0, 90]
)
status = create_rotation(
    [0, 0, 0]
)

rot = compute(Root, T_pose, status)

print(np.round(rot, 2))
print()

print(np.round(Rot2Euler(rot)))

[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]

[90.  0.  0.]


In [49]:
target = np.array(
    [[ 1.,  0.,  0.],
 [ 0.,  0. ,-1.],
 [ 0. , 1. , 0.]], dtype=np.float32
)
target

array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]], dtype=float32)

In [53]:
value_list = list(range(-180, 180, 10))


for x in value_list:
    for y in value_list:
        for z in value_list:
            rot = compute(
                create_rotation(
                    [x, y, z]
                ),
                T_pose,
                status
            )
            if np.round(rot, 1).all() == target.all():
                print(x, y, z)

-180 -180 -180
-180 -180 -170
-180 -180 -160
-180 -180 -150
-180 -180 -140
-180 -180 -130
-180 -180 -120
-180 -180 -110
-180 -180 -100
-180 -180 -90
-180 -180 -80
-180 -180 -70
-180 -180 -60
-180 -180 -50
-180 -180 -40
-180 -180 -30
-180 -180 -20
-180 -180 -10
-180 -180 0
-180 -180 10
-180 -180 20
-180 -180 30
-180 -180 40
-180 -180 50
-180 -180 60
-180 -180 70
-180 -180 80
-180 -180 90
-180 -180 100
-180 -180 110
-180 -180 120
-180 -180 130
-180 -180 140
-180 -180 150
-180 -180 160
-180 -180 170
-180 -170 -180
-180 -170 -170
-180 -170 -160
-180 -170 -150
-180 -170 -140
-180 -170 -130
-180 -170 -120
-180 -170 -110
-180 -170 -100
-180 -170 -90
-180 -170 -80
-180 -170 -70
-180 -170 -60
-180 -170 -50
-180 -170 -40
-180 -170 -30
-180 -170 -20
-180 -170 -10
-180 -170 0
-180 -170 10
-180 -170 20
-180 -170 30
-180 -170 40
-180 -170 50
-180 -170 60
-180 -170 70
-180 -170 80
-180 -170 90
-180 -170 100
-180 -170 110
-180 -170 120
-180 -170 130
-180 -170 140
-180 -170 150
-180 -170 160
-180 -170 

In [10]:
root_rot = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0],
], dtype=np.float32
)

euler_angles = np.radians([45, 0, 0])
r = Rotation.from_euler('xyz', euler_angles)
rotation_matrix = r.as_matrix()
rot = rotation_matrix.dot(root_rot )

print(rot)
print()

print(Rot2Euler(rot))

[[ 0.          0.          1.        ]
 [ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]]

[ 90. -45.  90.]


In [16]:
Rot2Euler(np.array([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, 1],
]))

array([  0.,   0., 180.])

In [18]:
a = np.array([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, 1],
])
Rot2Euler(np.linalg.inv(root_rot).dot(a))

C:\Users\stahp\AppData\Local\Temp\ipykernel_4312\974069873.py:11: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  return np.degrees(r.as_euler('xyz'))


array([-90.,  90.,   0.])

In [6]:
import numpy as np
from fairmotion.ops import conversions

conversions.Q2R(
    np.array([
        [0, 0, 0, 1],
        [0, 0, 1, 0],
    ])
).reshape(-1).shape

(18,)

In [ ]:
-137.58136127

In [17]:
rot = conversions.Q2R(np.array([ 0.029,  -0.01 , -0.269,  0.963]))
euler = Rot2Euler(rot)
euler[:2] = 0
rot = create_rotation(euler)
conversions.R2Q(rot)

array([ 0.        ,  0.        , -0.26909023,  0.96311497])